### ISSUE TITLE
java.lang.UnsupportedOperationException: null in DefaultIssueLocation.java:97

### ISSUE THREAD

**Issue by javadev** [detekt/sonar-kotlin#168]
Task :jacocoTestReport
> Task :sonar
The Data Dictionary is not configured for the PLSQL analyzer, which prevents rule(s) S3641, S3921, S3618, S3651 from raising issues. See https://docs.sonarcloud.io/advanced-setup/languages/pl-sql/
Could not report issue with code highlighting, using plain text instead. Check whether the product is outdated.
java.lang.UnsupportedOperationException: null
	at org.sonar.api.batch.sensor.issue.internal.DefaultIssueLocation.newMessageFormatting(DefaultIssueLocation.java:97)
	at org.sonarsource.kotlin.plugin.InputFileContextImpl.message(InputFileContext.kt:94)
	at org.sonarsource.kotlin.plugin.InputFileContextImpl.reportIssue(InputFileContext.kt:69)
	at org.sonarsource.kotlin.api.AbstractCheck.reportIssue$sonar_kotlin_plugin(AbstractCheck.kt:66)
	at org.sonarsource.kotlin.api.AbstractCheck.reportIssue$sonar_kotlin_plugin(AbstractCheck.kt:85)
	at org.sonarsource.kotlin.api.AbstractCheck.reportIssue$sonar_kotlin_plugin$default(AbstractCheck.kt:[80](https://github.com/javadev/LeetCode-in-Kotlin/actions/runs/5248853194/jobs/9480903321#step:5:81))
	at org.sonarsource.kotlin.checks.MapValuesShouldBeAccessedSafelyCheck.visitClass(MapValuesShouldBeAccessedSafelyCheck.kt:68)
	at org.sonarsource.kotlin.checks.MapValuesShouldBeAccessedSafelyCheck.visitClass(MapValuesShouldBeAccessedSafelyCheck.kt:39)
	at org.jetbrains.kotlin.psi.KtClass.accept(KtClass.kt:22)
	at org.sonarsource.kotlin.visiting.KtChecksVisitor$visit$1$1$1.invoke(KtChecksVisitor.kt:39)
	at org.sonarsource.kotlin.visiting.KtChecksVisitor$visit$1$1$1.invoke(KtChecksVisitor.kt:34)
	at

**Comment by javadev** [comment]
https://github.com/javadev/LeetCode-in-Kotlin/actions/runs/5248853194/jobs/9480903321

**Comment by javadev** [comment]
I kindly request that you investigate this matter and promptly resolve it.

**Comment by arturbosch** [comment]
This is an issue of the official sonar-kotlin plugin not sonar-detekt.
Historically this plugin was called sonar-kotlin before 2.0.
